# aws:
#   access_key_id: 123
#   secret_access_key: 345

# General for all environments

hello: Hello World!

emails_from: team@example.com

google:
  client_id: XXX
  client_secret: XXX

facebook:
  app_id: XXX
  app_secret: XXX

production:
  hello: Hello production!
  domain: example.com

development:
  hello: Hello dev!

test:
  hello: Hello test!

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: XXX
